# Generated by Django 5.1.5 on 2026-01-31 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_sp500',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AdjustedStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('adjusted_open', models.DecimalField(decimal_places=4, max_digits=10)),
                ('adjusted_high', models.DecimalField(decimal_places=4, max_digits=10)),
                ('adjusted_low', models.DecimalField(decimal_places=4, max_digits=10)),
                ('adjusted_close', models.DecimalField(decimal_places=4, max_digits=10)),
                ('adjusted_volume', models.BigIntegerField()),
                ('split_coefficient', models.DecimalField(decimal_places=4, default=1.0, help_text='Cumulative split adjustment coefficient', max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjusted_prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['stock', '-date'], name='stocks_adju_stock_i_fd08d2_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split_date', models.DateField(db_index=True)),
                ('split_ratio', models.DecimalField(decimal_places=4, help_text='Split ratio (e.g., 2.0 for 2-for-1 split, 0.5 for 1-for-2 reverse split)', max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='stocks.stock')),
            ],
            options={
                'ordering': ['-split_date'],
                'indexes': [models.Index(fields=['stock', '-split_date'], name='stocks_stoc_stock_i_f9937d_idx')],
                'unique_together': {('stock', 'split_date')},
            },
        ),
    ]
