# Generated by Django 5.1.5 on 2026-02-01 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_dailystock_dailystockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(blank=True, max_length=50)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('fiscal_year_end', models.CharField(blank=True, max_length=20)),
                ('market_capitalization', models.BigIntegerField(blank=True, null=True)),
                ('ebitda', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peg_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dividend_per_share', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue_per_share_ttm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('operating_margin_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_on_assets_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('return_on_equity_ttm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('revenue_ttm', models.BigIntegerField(blank=True, null=True)),
                ('gross_profit_ttm', models.BigIntegerField(blank=True, null=True)),
                ('quarterly_earnings_growth_yoy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('quarterly_revenue_growth_yoy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('analyst_target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trailing_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forward_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_sales_ratio_ttm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to_book_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('beta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_50_moving_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('day_200_moving_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('shares_float', models.BigIntegerField(blank=True, null=True)),
                ('percent_insiders', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('percent_institutions', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='stocks.stock')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
