# Generated by Django 5.1.5 on 2026-02-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_intradaystock_intradaystockprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('1D', '1 Day'), ('1W', '1 Week'), ('1M', '1 Month'), ('YTD', 'Year to Date'), ('6M', '6 Months'), ('1Y', '1 Year'), ('5Y', '5 Years')], max_length=5)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('end_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_change', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percent_change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data_source', models.CharField(default='weekly', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['period', '-percent_change'], name='stocks_stoc_period_7fa333_idx'), models.Index(fields=['period', 'percent_change'], name='stocks_stoc_period_426595_idx')],
                'unique_together': {('symbol', 'period')},
            },
        ),
    ]
