# Generated by Django 5.1.5 on 2026-02-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stockperformance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockoverview',
            name='analyst_rating_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='analyst_rating_hold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='analyst_rating_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='analyst_rating_strong_buy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='analyst_rating_strong_sell',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='cik',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='diluted_eps_ttm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='ev_to_ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='ev_to_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='ex_dividend_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='latest_quarter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockoverview',
            name='official_site',
            field=models.URLField(blank=True),
        ),
    ]
