# Generated by Django 5.1.5 on 2026-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stockoverview_analyst_rating_buy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='logo_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
