# Generated by Django 5.1.5 on 2026-03-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SECFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('cik', models.CharField(db_index=True, max_length=20)),
                ('accession_number', models.CharField(max_length=30, unique=True)),
                ('filing_type', models.CharField(choices=[('10-K', 'Annual Report'), ('10-Q', 'Quarterly Report'), ('8-K', 'Current Report'), ('20-F', 'Annual Report (Foreign)'), ('6-K', 'Current Report (Foreign)')], db_index=True, max_length=10)),
                ('filing_date', models.DateField(db_index=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('filing_url', models.URLField(max_length=500)),
                ('document_url', models.URLField(blank=True, max_length=500)),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('raw_text', models.TextField(blank=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['symbol', '-filing_date'], name='rag_secfili_symbol_2333bd_idx'), models.Index(fields=['filing_type', '-filing_date'], name='rag_secfili_filing__b6f401_idx'), models.Index(fields=['symbol', 'filing_type', '-filing_date'], name='rag_secfili_symbol_da5784_idx')],
            },
        ),
    ]
