# Generated by Django 5.1.5 on 2026-03-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secfiling',
            name='exhibits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='secfiling',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='secfiling',
            name='raw_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='secfiling',
            name='tables',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
